[package]
authors = ["Shinichi Morimoto <shnmorimoto@gmail.com>"]
edition = "2018"
name = "rmonkey"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
once_cell = "1.7"
